Rui/update circuit init logic
node-red-quantum/node-red-contrib-quantum pull request #115
Opened 2021-08-31 20:11 UTC by bbaayezi

### Purpose

Simplify quantum circuit initialisation logic without the use of event listeners and proxies. Proposed by issue #112.

### Changes

Remove the use of `quantumCircuit` object and `quantumCircuitConfig` object in state manager. Send an explicit boolean message `shouldInitCircuit` to the last output of the quantum circuit node to initialise quantum circuit.

`validateRegisterStrucutre` in `errors.js` can be removed.

2021-08-31 21:07 UTC, louislefevre requested changes

2021-08-31 21:07 UTC, louislefevre commented on nodes/quantum/classical-register/classical-register.js
> +
Remove these trailing spaces

2021-08-31 21:07 UTC, louislefevre commented on nodes/quantum/classical-register/classical-register.js
> +      await shell.execute(script, async (err) => {
```suggestion
      await shell.execute(script, (err) => {
```
Can remove `async` operator here

2021-08-31 22:40 UTC, louislefevre approved these changes

2021-09-01 14:51 UTC, KhesimReid approved these changes

2021-09-01 15:20 UTC, Theo-Reignier approved these changes

2021-09-01 16:36 UTC, merged